// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SearchBugs.Persistence;

#nullable disable

namespace SearchBugs.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260301184531_AddPullRequestTable")]
    partial class AddPullRequestTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SearchBugs.Domain.AuditLogs.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("is_success");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on_utc");

                    b.Property<string>("RequestData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_data");

                    b.Property<string>("RequestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("request_name");

                    b.Property<string>("ResponseData")
                        .HasColumnType("text")
                        .HasColumnName("response_data");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("CreatedOnUtc")
                        .HasDatabaseName("ix_audit_logs_created_on_utc");

                    b.HasIndex("IsSuccess")
                        .HasDatabaseName("ix_audit_logs_is_success");

                    b.HasIndex("RequestName")
                        .HasDatabaseName("ix_audit_logs_request_name");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("SearchBugs.Domain.Bugs.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BugId")
                        .HasColumnType("uuid")
                        .HasColumnName("bug_id");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("file_name");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on_utc");

                    b.HasKey("Id")
                        .HasName("pk_attachment");

                    b.HasIndex("BugId")
                        .HasDatabaseName("ix_attachment_bug_id");

                    b.ToTable("attachment", (string)null);
                });

            modelBuilder.Entity("SearchBugs.Domain.Bugs.Bug", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on_utc");

                    b.Property<int>("PriorityId")
                        .HasColumnType("integer")
                        .HasColumnName("priority_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("severity");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_bug");

                    b.HasIndex("AssigneeId")
                        .HasDatabaseName("ix_bug_assignee_id");

                    b.HasIndex("PriorityId")
                        .HasDatabaseName("ix_bug_priority_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_bug_project_id");

                    b.HasIndex("ReporterId")
                        .HasDatabaseName("ix_bug_reporter_id");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_bug_status_id");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_bug_title");

                    b.ToTable("bug", (string)null);
                });

            modelBuilder.Entity("SearchBugs.Domain.Bugs.BugCustomField", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BugId")
                        .HasColumnType("uuid")
                        .HasColumnName("bug_id");

                    b.Property<Guid>("CustomFieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("custom_field_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_bug_custom_field");

                    b.HasIndex("BugId")
                        .HasDatabaseName("ix_bug_custom_field_bug_id");

                    b.HasIndex("CustomFieldId")
                        .HasDatabaseName("ix_bug_custom_field_custom_field_id");

                    b.ToTable("bug_custom_field", (string)null);
                });

            modelBuilder.Entity("SearchBugs.Domain.Bugs.BugHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BugId")
                        .HasColumnType("uuid")
                        .HasColumnName("bug_id");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at_utc");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by");

                    b.Property<string>("FieldChanged")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("field_changed");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("old_value");

                    b.HasKey("Id")
                        .HasName("pk_bug_history");

                    b.HasIndex("BugId")
                        .HasDatabaseName("ix_bug_history_bug_id");

                    b.HasIndex("ChangedBy")
                        .HasDatabaseName("ix_bug_history_changed_by");

                    b.ToTable("bug_history", (string)null);
                });

            modelBuilder.Entity("SearchBugs.Domain.Bugs.BugPriority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_bug_priority");

                    b.ToTable("bug_priority", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Low"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            Name = "High"
                        });
                });

            modelBuilder.Entity("SearchBugs.Domain.Bugs.BugStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_bug_status");

                    b.ToTable("bug_status", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Open"
                        },
                        new
                        {
                            Id = 2,
                            Name = "In Progress"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Resolved"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Closed"
                        });
                });

            modelBuilder.Entity("SearchBugs.Domain.Bugs.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BugId")
                        .HasColumnType("uuid")
                        .HasColumnName("bug_id");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment_text");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_comment");

                    b.HasIndex("BugId")
                        .HasDatabaseName("ix_comment_bug_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_comment_user_id");

                    b.ToTable("comment", (string)null);
                });

            modelBuilder.Entity("SearchBugs.Domain.Bugs.CustomField", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("field_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("pk_custom_field");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_custom_field_name");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_custom_field_project_id");

                    b.ToTable("custom_field", (string)null);
                });

            modelBuilder.Entity("SearchBugs.Domain.Bugs.TimeTracking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BugId")
                        .HasColumnType("uuid")
                        .HasColumnName("bug_id");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_at");

                    b.Property<DateTime?>("TimeSpent")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_spent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_time_track");

                    b.HasIndex("BugId")
                        .HasDatabaseName("ix_time_track_bug_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_time_track_user_id");

                    b.ToTable("time_track", (string)null);
                });

            modelBuilder.Entity("SearchBugs.Domain.Git.PullRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("MergedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("merged_at_utc");

                    b.Property<Guid?>("MergedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("merged_by");

                    b.Property<string>("RepoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("repo_url");

                    b.Property<string>("SourceBranch")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source_branch");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TargetBranch")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("target_branch");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_pull_request");

                    b.ToTable("pull_request", (string)null);
                });

            modelBuilder.Entity("SearchBugs.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BugId")
                        .HasColumnType("uuid")
                        .HasColumnName("bug_id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notification");

                    b.HasIndex("BugId")
                        .HasDatabaseName("ix_notification_bug_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notification_user_id");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("SearchBugs.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_project");

                    b.ToTable("project", (string)null);
                });

            modelBuilder.Entity("SearchBugs.Domain.Projects.ProjectRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_project_role");

                    b.ToTable("project_role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Owner"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Developer"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tester"
                        });
                });

            modelBuilder.Entity("SearchBugs.Domain.Projects.ProjectRoleUser", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("ProjectRoleId")
                        .HasColumnType("integer")
                        .HasColumnName("project_role_id");

                    b.HasKey("ProjectId", "UserId", "RoleId")
                        .HasName("pk_project_role_user");

                    b.HasIndex("ProjectRoleId")
                        .HasDatabaseName("ix_project_role_user_project_role_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_project_role_user_user_id");

                    b.ToTable("project_role_user", (string)null);
                });

            modelBuilder.Entity("SearchBugs.Domain.Repositories.BugRepo", b =>
                {
                    b.Property<Guid>("BugId")
                        .HasColumnType("uuid")
                        .HasColumnName("bug_id");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("repository_id");

                    b.HasKey("BugId", "RepositoryId")
                        .HasName("pk_bug_repository");

                    b.HasIndex("BugId")
                        .HasDatabaseName("ix_bug_repository_bug_id");

                    b.HasIndex("RepositoryId")
                        .HasDatabaseName("ix_bug_repository_repository_id");

                    b.ToTable("bug_repository", (string)null);
                });

            modelBuilder.Entity("SearchBugs.Domain.Repositories.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_repository");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_repository_project_id");

                    b.HasIndex("Url")
                        .IsUnique()
                        .HasDatabaseName("ix_repository_url");

                    b.ToTable("repository", (string)null);
                });

            modelBuilder.Entity("SearchBugs.Domain.Roles.Permission", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_permission");

                    b.ToTable("permission", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Can create a new user",
                            Name = "CreateUser"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Can view user details",
                            Name = "ViewUserDetails"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Can update user details",
                            Name = "UpdateUser"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Can delete a user",
                            Name = "DeleteUser"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Can authenticate a user",
                            Name = "AuthenticateUser"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Can change user password",
                            Name = "ChangeUserPassword"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Can list all users",
                            Name = "ListAllUsers"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Can Create Project",
                            Name = "CreateProject"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Can View Project Details",
                            Name = "ViewProjectDetails"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Can Update Project",
                            Name = "UpdateProject"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Can Delete Project",
                            Name = "DeleteProject"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Can List All Projects",
                            Name = "ListAllProjects"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Can Create Bug",
                            Name = "CreateBug"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Can View Bug Details",
                            Name = "ViewBugDetails"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Can Update Bug",
                            Name = "UpdateBug"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Can Delete Bug",
                            Name = "DeleteBug"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Can List All Bugs",
                            Name = "ListAllBugs"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Can Add Comment To Bug",
                            Name = "AddCommentToBug"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Can View Bug Comments",
                            Name = "ViewBugComments"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Can Add Attachment To Bug",
                            Name = "AddAttachmentToBug"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Can View Bug Attachments",
                            Name = "ViewBugAttachments"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Can View Bug History",
                            Name = "ViewBugHistory"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Can Track Time Spent On Bug",
                            Name = "TrackTimeSpentOnBug"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Can View Time Spent On Bug",
                            Name = "ViewTimeSpentOnBug"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Can Add Custom Field To Bug",
                            Name = "AddCustomFieldToBug"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Can View Custom Field On Bug",
                            Name = "ViewCustomFieldOnBug"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Can View Notification",
                            Name = "ViewNotification"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Can Delete Notification",
                            Name = "DeleteNotification"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Can Mark Notification As Read",
                            Name = "MarkNotificationAsRead"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Can Create Repository",
                            Name = "CreateRepository"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Can View Repository Details",
                            Name = "ViewRepositoryDetails"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Can Update Repository",
                            Name = "UpdateRepository"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Can Delete Repository",
                            Name = "DeleteRepository"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Can List All Repositories",
                            Name = "ListAllRepositories"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Can Link Bug To Repository",
                            Name = "LinkBugToRepository"
                        },
                        new
                        {
                            Id = 37,
                            Description = "Can View Bug Repository",
                            Name = "ViewBugRepository"
                        },
                        new
                        {
                            Id = 38,
                            Description = "Can View Roles",
                            Name = "ViewRoles"
                        },
                        new
                        {
                            Id = 39,
                            Description = "Can View Permissions",
                            Name = "ViewPermissions"
                        },
                        new
                        {
                            Id = 40,
                            Description = "Can Assign Permission To Role",
                            Name = "AssignPermissionToRole"
                        },
                        new
                        {
                            Id = 41,
                            Description = "Can Remove Permission From Role",
                            Name = "RemovePermissionFromRole"
                        },
                        new
                        {
                            Id = 42,
                            Description = "Can View Role Permissions",
                            Name = "ViewRolePermissions"
                        },
                        new
                        {
                            Id = 43,
                            Description = "Can Assign Role To User",
                            Name = "AssignRoleToUser"
                        },
                        new
                        {
                            Id = 44,
                            Description = "Can Remove Role From User",
                            Name = "RemoveRoleFromUser"
                        });
                });

            modelBuilder.Entity("SearchBugs.Domain.Roles.Role", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.ToTable("role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Project Manager"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Developer"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Reporter"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Guest"
                        });
                });

            modelBuilder.Entity("SearchBugs.Domain.Roles.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permission");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permission_permission_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_permission_role_id");

                    b.ToTable("role_permission", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 5,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 17
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 19
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 21
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 22
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 26
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 17
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 18
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 19
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 20
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 21
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 22
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 24
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 26
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 28
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 30
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 17
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 18
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 19
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 20
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 21
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 22
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 23
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 24
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 25
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 26
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 28
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 30
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 32
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 36
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 37
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 16
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 17
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 18
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 19
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 20
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 21
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 22
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 23
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 24
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 25
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 26
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 28
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 30
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 29
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 31
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 32
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 33
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 34
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 35
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 36
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 37
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 16
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 17
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 18
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 19
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 20
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 21
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 22
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 23
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 24
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 25
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 26
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 28
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 29
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 30
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 31
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 32
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 33
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 34
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 35
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 36
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 37
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 38
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 39
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 40
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 41
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 42
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 43
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 44
                        });
                });

            modelBuilder.Entity("SearchBugs.Domain.Users.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("bio");

                    b.Property<string>("Company")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("GitHubProfile")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("git_hub_profile");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_public");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("job_title");

                    b.Property<string>("LinkedInProfile")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("linked_in_profile");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("location");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on_utc");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("PreferredLanguage")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("preferred_language");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone");

                    b.Property<string>("TwitterHandle")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("twitter_handle");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_profiles");

                    b.HasIndex("CreatedOnUtc")
                        .HasDatabaseName("ix_profiles_created_on_utc");

                    b.HasIndex("IsPublic")
                        .HasDatabaseName("ix_profiles_is_public");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_profiles_user_id");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("SearchBugs.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on_utc");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_reset_token");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_reset_token_expiry");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("SearchBugs.Domain.Users.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_role");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_role_role_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_role_user_id");

                    b.ToTable("user_role", (string)null);
                });

            modelBuilder.Entity("SearchBugs.Domain.Bugs.Attachment", b =>
                {
                    b.HasOne("SearchBugs.Domain.Bugs.Bug", null)
                        .WithMany("Attachments")
                        .HasForeignKey("BugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attachment_bug_bug_id");
                });

            modelBuilder.Entity("SearchBugs.Domain.Bugs.Bug", b =>
                {
                    b.HasOne("SearchBugs.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bug_user_assignee_id");

                    b.HasOne("SearchBugs.Domain.Bugs.BugPriority", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bug_bug_priorities_priority_id");

                    b.HasOne("SearchBugs.Domain.Projects.Project", null)
                        .WithMany("Bugs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bug_project_project_id");

                    b.HasOne("SearchBugs.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bug_user_reporter_id");

                    b.HasOne("SearchBugs.Domain.Bugs.BugStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bug_bug_statuses_status_id");

                    b.Navigation("Priority");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SearchBugs.Domain.Bugs.BugCustomField", b =>
                {
                    b.HasOne("SearchBugs.Domain.Bugs.Bug", "Bug")
                        .WithMany("BugCustomFields")
                        .HasForeignKey("BugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bug_custom_field_bug_bug_id");

                    b.HasOne("SearchBugs.Domain.Bugs.CustomField", "CustomField")
                        .WithMany("BugCustomFields")
                        .HasForeignKey("CustomFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bug_custom_field_custom_field_custom_field_id");

                    b.Navigation("Bug");

                    b.Navigation("CustomField");
                });

            modelBuilder.Entity("SearchBugs.Domain.Bugs.BugHistory", b =>
                {
                    b.HasOne("SearchBugs.Domain.Bugs.Bug", null)
                        .WithMany("BugHistories")
                        .HasForeignKey("BugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bug_history_bug_bug_id");

                    b.HasOne("SearchBugs.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bug_history_user_changed_by");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SearchBugs.Domain.Bugs.Comment", b =>
                {
                    b.HasOne("SearchBugs.Domain.Bugs.Bug", null)
                        .WithMany("Comments")
                        .HasForeignKey("BugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_bug_bug_id");

                    b.HasOne("SearchBugs.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SearchBugs.Domain.Bugs.CustomField", b =>
                {
                    b.HasOne("SearchBugs.Domain.Projects.Project", "Project")
                        .WithMany("CustomsFields")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_custom_field_project_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SearchBugs.Domain.Bugs.TimeTracking", b =>
                {
                    b.HasOne("SearchBugs.Domain.Bugs.Bug", null)
                        .WithMany("TimeTracking")
                        .HasForeignKey("BugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_time_track_bug_bug_id");

                    b.HasOne("SearchBugs.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_time_track_user_user_id");
                });

            modelBuilder.Entity("SearchBugs.Domain.Notifications.Notification", b =>
                {
                    b.HasOne("SearchBugs.Domain.Bugs.Bug", null)
                        .WithMany()
                        .HasForeignKey("BugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_bug_bug_id");

                    b.HasOne("SearchBugs.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_user_user_id");
                });

            modelBuilder.Entity("SearchBugs.Domain.Projects.ProjectRoleUser", b =>
                {
                    b.HasOne("SearchBugs.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_role_user_project_project_id");

                    b.HasOne("SearchBugs.Domain.Projects.ProjectRole", null)
                        .WithMany()
                        .HasForeignKey("ProjectRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_role_user_project_role_project_role_id");

                    b.HasOne("SearchBugs.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_role_user_user_user_id");
                });

            modelBuilder.Entity("SearchBugs.Domain.Repositories.BugRepo", b =>
                {
                    b.HasOne("SearchBugs.Domain.Bugs.Bug", null)
                        .WithMany()
                        .HasForeignKey("BugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bug_repository_bug_bug_id");

                    b.HasOne("SearchBugs.Domain.Repositories.Repository", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bug_repository_repository_repository_id");
                });

            modelBuilder.Entity("SearchBugs.Domain.Repositories.Repository", b =>
                {
                    b.HasOne("SearchBugs.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_repository_project_project_id");
                });

            modelBuilder.Entity("SearchBugs.Domain.Roles.RolePermission", b =>
                {
                    b.HasOne("SearchBugs.Domain.Roles.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permission_permission_permission_id");

                    b.HasOne("SearchBugs.Domain.Roles.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permission_role_role_id");
                });

            modelBuilder.Entity("SearchBugs.Domain.Users.Profile", b =>
                {
                    b.HasOne("SearchBugs.Domain.Users.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("SearchBugs.Domain.Users.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profiles_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SearchBugs.Domain.Users.User", b =>
                {
                    b.OwnsOne("SearchBugs.Domain.Users.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(225)
                                .HasColumnType("character varying(225)")
                                .HasColumnName("email_value");

                            b1.HasKey("UserId");

                            b1.ToTable("user");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_user_user_id");
                        });

                    b.OwnsOne("SearchBugs.Domain.Users.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name_first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name_last_name");

                            b1.HasKey("UserId");

                            b1.ToTable("user");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_user_user_id");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("SearchBugs.Domain.Users.UserRole", b =>
                {
                    b.HasOne("SearchBugs.Domain.Roles.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_role_role_id");

                    b.HasOne("SearchBugs.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_user_user_id");
                });

            modelBuilder.Entity("SearchBugs.Domain.Bugs.Bug", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("BugCustomFields");

                    b.Navigation("BugHistories");

                    b.Navigation("Comments");

                    b.Navigation("TimeTracking");
                });

            modelBuilder.Entity("SearchBugs.Domain.Bugs.CustomField", b =>
                {
                    b.Navigation("BugCustomFields");
                });

            modelBuilder.Entity("SearchBugs.Domain.Projects.Project", b =>
                {
                    b.Navigation("Bugs");

                    b.Navigation("CustomsFields");
                });

            modelBuilder.Entity("SearchBugs.Domain.Users.User", b =>
                {
                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
